version: 0.2

phases:
  install:
    commands:
      - yum -y groupinstall "Development Tools"
      - yum -y install libglvnd-glx libXi
      - npm install -g gatsby
  build:
    commands:
      - npm install
      - gatsby build
artifacts:
  files:
    - '**/*'
  name: slashdev.org-$(date +%Y%m%d).zip