name: SlashDev IaC
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  terraform-validate:
    runs-on: ubuntu-22.04
    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install asdf tools
        uses: asdf-vm/actions/install@v3
      - name: Terraform Validate
        run: "terraform init && terraform validate"
      - name: Terraform Plan
        run: "terraform plan"
