name: SlashDev IaC
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  terraform-validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3
      - name: Cache asdf
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: asdf-${{ hashFiles('**/.tool-versions') }}
      - name: Install asdf tools
        if: steps.cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3
      - name: Terraform Validate/Plan
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          cd terraform
          terraform init && terraform validate
          terraform plan
